events {
    worker_connections 1024;
}

http {
    # Redirección global de HTTP (Puerto 80) a HTTPS seguro
    server {
        listen 80;
        server_name sso.tfm.local mtls.sso.tfm.local;
        return 301 https://$host$request_uri;
    }

    # PUERTA 1: ACCESO SIN CERTIFICADO (Para App 1 y App 2 - Puerto 5000/5001)
    server {
        listen 443 ssl;
        server_name sso.tfm.local;

        # Certificados SSL del servidor proxy
        ssl_certificate /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Seguridad estricta: NO se solicita certificado al cliente
        ssl_verify_client off;

        location / {
            proxy_pass http://keycloak_node1:8080;
            
            # Cabeceras estándar necesarias para el funcionamiento de Keycloak
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    # PUERTA 2: ACCESO CON CERTIFICADO (Exclusivo para App 3 con mTLS)
    server {
        listen 443 ssl;
        server_name mtls.sso.tfm.local;
        # Enviamos el certificado completo codificado para que Keycloak lo valide
        proxy_set_header ssl-client-cert $ssl_client_escaped_cert;

        # Mismos certificados SSL del servidor proxy
        ssl_certificate /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Seguridad robusta: OBLIGATORIO presentar certificado de cliente
        ssl_client_certificate /etc/nginx/certs/ca.crt;
        ssl_verify_client optional;

        location / {
            proxy_pass http://keycloak_node1:8080;

            # Inyección forzosa de atributos criptográficos verificados
            proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
            proxy_set_header X-SSL-Client-Cert-Subject-DN $ssl_client_s_dn;

            # Cabeceras estándar de proxy inverso
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}